Worlds: [mine, mine_nether, mine_the_end]
PlayerCooldown: 10
Biomes:
- Name: Plains
  Biomes:
  - PLAINS
  - SUNFLOWER_PLAINS
- Name: Forest
  Biomes:
  - FOREST
  - BIRCH_FOREST
  - DARK_FOREST
  - FLOWER_FOREST
  - OLD_GROWTH_BIRCH_FOREST
  - WINDSWEPT_FOREST
- Name: Windswept
  Biomes:
  - WINDSWEPT_HILLS
  - WINDSWEPT_GRAVELLY_HILLS
- Name: Mountains
  Biomes:
  - SNOWY_SLOPES
  - MEADOW
  - GROVE
  - JAGGED_PEAKS
  - FROZEN_PEAKS
  - STONY_PEAKS
- Name: Dark Forest
  Biomes:
  - DARK_FOREST
- Name: Flower Forest
  Biomes:
  - FLOWER_FOREST
- Name: Swamp
  Biomes:
  - SWAMP
- Name: Taiga
  Biomes:
  - TAIGA
  - SNOWY_TAIGA
  - OLD_GROWTH_PINE_TAIGA
  - OLD_GROWTH_SPRUCE_TAIGA
- Name: Desert
  Biomes:
  - DESERT
- Name: Jungle
  Biomes:
  - JUNGLE
  - SPARSE_JUNGLE
- Name: Bamboo
  Biomes:
  - BAMBOO_JUNGLE
- Name: Mesa
  Biomes:
  - BADLANDS
  - ERODED_BADLANDS
  - WOODED_BADLANDS
- Name: Savanna
  Biomes:
  - SAVANNA
  - SAVANNA_PLATEAU
  - WINDSWEPT_SAVANNA
- Name: Cold
  Biomes:
  - ICE_SPIKES
  - SNOWY_BEACH
  - SNOWY_TAIGA
  - FROZEN_OCEAN
  - COLD_OCEAN
  - FROZEN_RIVER
  - SNOWY_PLAINS
  - SNOWY_SLOPES
  - FROZEN_PEAKS
- Name: Frozen
  Biomes:
  - FROZEN_OCEAN
  - FROZEN_RIVER
  - ICE_SPIKES
  - DEEP_FROZEN_OCEAN
- Name: Ocean
  Biomes:
  - OCEAN
  - FROZEN_OCEAN
  - DEEP_OCEAN
  - WARM_OCEAN
  - LUKEWARM_OCEAN
  - COLD_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN
  - BEACH
  - STONY_SHORE
- Name: River
  Biomes:
  - RIVER
  - FROZEN_RIVER
- Name: Mooshroom
  Biomes:
  - MUSHROOM_FIELDS
- Name: Nether
  Biomes:
  - NETHER_WASTES
  - SOUL_SAND_VALLEY
  - CRIMSON_FOREST
  - WARPED_FOREST
  - BASALT_DELTAS
