Worlds: [ mine, mine_nether ]
CrawlerInterval: 20
BiomeDistance: 256
PlayerCooldown: 10
Biomes:
- Name: Plains
  Biomes:
  - PLAINS
  - SUNFLOWER_PLAINS
- Name: Forest
  Biomes:
  - FOREST
  - BIRCH_FOREST
  - BIRCH_FOREST_HILLS
  - DARK_FOREST
  - FLOWER_FOREST
  - TALL_BIRCH_FOREST
  - DARK_FOREST_HILLS
  - WOODED_HILLS
  - WOODED_MOUNTAINS
  - WOODED_BADLANDS_PLATEAU
  - MODIFIED_WOODED_BADLANDS_PLATEAU
- Name: Swamp
  Biomes:
  - SWAMP
  - SWAMP_HILLS
- Name: Taiga
  Biomes:
  - TAIGA
  - TAIGA_HILLS
  - SNOWY_TAIGA
  - SNOWY_TAIGA_HILLS
  - GIANT_TREE_TAIGA
  - GIANT_TREE_TAIGA_HILLS
  - TAIGA_MOUNTAINS
  - SNOWY_TAIGA_MOUNTAINS
  - GIANT_SPRUCE_TAIGA
  - GIANT_SPRUCE_TAIGA_HILLS
- Name: Desert
  Biomes:
  - DESERT
  - DESERT_HILLS
  - DESERT_LAKES
- Name: Mesa
  Biomes:
  - BADLANDS
  - WOODED_BADLANDS_PLATEAU
  - BADLANDS_PLATEAU
  - ERODED_BADLANDS
  - MODIFIED_WOODED_BADLANDS_PLATEAU
  - MODIFIED_BADLANDS_PLATEAU
- Name: Cold
  Biomes:
  - ICE_SPIKES
  - SNOWY_TUNDRA
  - SNOWY_MOUNTAINS
  - SNOWY_BEACH
  - SNOWY_TAIGA
  - SNOWY_TAIGA_HILLS
  - SNOWY_TAIGA_MOUNTAINS
- Name: Ocean
  Biomes:
  - OCEAN
  - FROZEN_OCEAN
  - DEEP_OCEAN
  - WARM_OCEAN
  - LUKEWARM_OCEAN
  - COLD_OCEAN
  - DEEP_WARM_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN
  - BEACH
- Name: Nether
  Biomes:
  - NETHER_WASTES
  - SOUL_SAND_VALLEY
  - CRIMSON_FOREST
  - WARPED_FOREST
  - BASALT_DELTAS
