World: Resource
Center: [ 0, 0 ]
Radius: 2000
Biomes:
- PLAINS
- TAIGA
- JUNGLE
- MESA
- DESERT
- ICE_PLAINS_SPIKES
- BEACH
- FOREST
- BIRCH_FOREST
- ROOFED_FOREST
- EXTREME_HILLS
- FLOWER_FOREST
- SUNFLOWER_PLAINS