main: com.winthier.resource.ResourcePlugin
name: Resource

version: 0.1
api-version: '1.21'

description: Warp to resource biomes
author: StarTux
website: https://cavetale.com

depend:
- Core
- Mytems
softdepend:
- Structure

commands:

  resource:
    aliases: [mine]
    description: User interface
    permission: resource.resource
    usage: /mine [biome]

  resourceadmin:
    aliases: [mineadmin]
    description: Admin interface
    permission: resource.admin
    usage: /mineadmin

permissions:

  resource.resource:
    description: Use /resource
    default: op

  resource.nocooldown:
    description: Skip the cooldown
    default: op

  resource.admin:
    description: Use admin subcommands
    default: op

  resource.back:
    description: Store back location
    default: true